import { UserRole } from '../types';

export type PermissionAction =
  | 'VIEW'
  | 'CREATE'
  | 'UPDATE'
  | 'DELETE'
  | 'APPROVE'
  | 'EXPORT'
  | 'PRINT'
  | 'MANAGE';

export type PermissionResource =
  | 'STUDENTS'
  | 'GUARDIANS'
  | 'ADMISSION'
  | 'ACADEMICS'
  | 'ACADEMIC_YEARS'
  | 'FACULTY_RESEARCH'
  | 'FACILITIES'
  | 'EXAMINATIONS'
  | 'MARKS_ENTRY'
  | 'TRANSCRIPTS'
  | 'ATTENDANCE'
  | 'TIMETABLE'
  | 'FEES_INVOICES'
  | 'ACCOUNTING_LEDGER'
  | 'EMPLOYEES'
  | 'PAYROLL'
  | 'LEAVES'
  | 'HIFZ_TRACKER'
  | 'THESIS_RESEARCH'
  | 'LIBRARY'
  | 'TRANSPORT'
  | 'HOSTEL'
  | 'CANTEEN'
  | 'PROCUREMENT'
  | 'COMMUNICATION'
  | 'AI_COPILOT'
  | 'REPORTS'
  | 'SETTINGS'
  | 'AUDIT_LOGS'
  | 'TENANTS'
  | 'POSITION'
  | 'RECRUITMENT'
  | 'CANDIDATE'
  | 'ATTENDANCE_HR'
  | 'SHIFT'
  | 'OVERTIME'
  | 'PERFORMANCE'
  | 'TRAINING'
  | 'DISCIPLINE'
  | 'GRIEVANCE'
  | 'SEPARATION'
  | 'INVENTORY'
  | 'WAREHOUSE'
  | 'ASSET'
  | 'MAINTENANCE'
  | 'VISITOR'
  | 'GATE'
  | 'FACILITY_BOOKING'
  | 'LMS_COURSE'
  | 'LESSON'
  | 'HOMEWORK'
  | 'ASSIGNMENT'
  | 'SUBMISSION'
  | 'QUESTION_BANK'
  | 'QUIZ'
  | 'ONLINE_CLASS'
  | 'DISCUSSION'
  | 'GRADEBOOK'
  | 'LEARNING_ANALYTICS'
  | 'REPORT'
  | 'REPORT_DATASET'
  | 'DASHBOARD'
  | 'REGULATORY_REPORT'
  | 'REGULATORY_TEMPLATE'
  | 'DATA_QUALITY'
  | 'REPORT_EXPORT'
  | 'REPORT_SCHEDULE';

// Permission Matrix mapping Role -> Resource -> Actions[]
export const ROLE_PERMISSIONS: Record<UserRole, Partial<Record<PermissionResource, PermissionAction[]>>> = {
  PLATFORM_SUPER_ADMIN: {
    TENANTS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SETTINGS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    AUDIT_LOGS: ['VIEW', 'EXPORT', 'PRINT', 'MANAGE'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  SUPER_ADMIN: {
    TENANTS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SETTINGS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    AUDIT_LOGS: ['VIEW', 'EXPORT', 'PRINT', 'MANAGE'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  PLATFORM_ADMIN: {
    TENANTS: ['VIEW', 'CREATE', 'UPDATE', 'EXPORT', 'PRINT'],
    SETTINGS: ['VIEW', 'UPDATE'],
    REPORTS: ['VIEW', 'EXPORT']
  },
  SUPPORT_ADMIN: {
    TENANTS: ['VIEW'],
    REPORTS: ['VIEW']
  },
  BILLING_ADMIN: {
    TENANTS: ['VIEW'],
    FEES_INVOICES: ['VIEW', 'EXPORT'],
    REPORTS: ['VIEW', 'EXPORT']
  },
  SALES_ADMIN: {
    TENANTS: ['VIEW', 'CREATE'],
    REPORTS: ['VIEW']
  },

  // Institution Leadership
  OWNER: {
    STUDENTS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    FEES_INVOICES: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ACCOUNTING_LEDGER: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EXAMINATIONS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PAYROLL: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SETTINGS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    AUDIT_LOGS: ['VIEW', 'EXPORT', 'PRINT']
  },
  CHAIRMAN: {
    STUDENTS: ['VIEW', 'EXPORT', 'PRINT'],
    FEES_INVOICES: ['VIEW', 'APPROVE', 'EXPORT'],
    ACCOUNTING_LEDGER: ['VIEW', 'APPROVE', 'EXPORT'],
    PAYROLL: ['VIEW', 'APPROVE', 'EXPORT'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  TRUSTEE: {
    STUDENTS: ['VIEW', 'EXPORT'],
    ACCOUNTING_LEDGER: ['VIEW', 'EXPORT'],
    REPORTS: ['VIEW', 'EXPORT']
  },
  VICE_CHANCELLOR: {
    STUDENTS: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EXAMINATIONS: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    THESIS_RESEARCH: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EMPLOYEES: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PAYROLL: ['VIEW', 'APPROVE', 'EXPORT'],
    LEAVES: ['VIEW', 'APPROVE'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  PRO_VICE_CHANCELLOR: {
    STUDENTS: ['VIEW', 'APPROVE', 'EXPORT'],
    EXAMINATIONS: ['VIEW', 'APPROVE', 'EXPORT'],
    THESIS_RESEARCH: ['VIEW', 'APPROVE', 'EXPORT']
  },
  REGISTRAR: {
    STUDENTS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    ADMISSION: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EMPLOYEES: ['VIEW', 'CREATE', 'UPDATE', 'EXPORT'],
    TRANSCRIPTS: ['VIEW', 'CREATE', 'APPROVE', 'EXPORT', 'PRINT']
  },
  PRINCIPAL: {
    LMS_COURSE: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LESSON: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    HOMEWORK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ASSIGNMENT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SUBMISSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUESTION_BANK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUIZ: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ONLINE_CLASS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    DISCUSSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    GRADEBOOK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LEARNING_ANALYTICS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    STUDENTS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ADMISSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EXAMINATIONS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    MARKS_ENTRY: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT'],
    FEES_INVOICES: ['VIEW', 'CREATE', 'APPROVE', 'EXPORT', 'PRINT'],
    ACCOUNTING_LEDGER: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT'],
    EMPLOYEES: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PAYROLL: ['VIEW', 'APPROVE', 'EXPORT', 'PRINT'],
    LEAVES: ['VIEW', 'APPROVE'],
    HIFZ_TRACKER: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SETTINGS: ['VIEW', 'UPDATE', 'MANAGE'],
    AUDIT_LOGS: ['VIEW', 'EXPORT'],
    POSITION: ['VIEW', 'APPROVE', 'EXPORT'],
    RECRUITMENT: ['VIEW', 'APPROVE', 'EXPORT'],
    CANDIDATE: ['VIEW', 'APPROVE'],
    ATTENDANCE_HR: ['VIEW', 'APPROVE', 'EXPORT'],
    SHIFT: ['VIEW', 'APPROVE'],
    OVERTIME: ['VIEW', 'APPROVE'],
    PERFORMANCE: ['VIEW', 'APPROVE', 'EXPORT'],
    TRAINING: ['VIEW', 'APPROVE'],
    DISCIPLINE: ['VIEW', 'APPROVE', 'MANAGE'],
    GRIEVANCE: ['VIEW', 'APPROVE'],
    SEPARATION: ['VIEW', 'APPROVE']
  },
  VICE_PRINCIPAL: {
    STUDENTS: ['VIEW', 'CREATE', 'UPDATE', 'EXPORT', 'PRINT'],
    EXAMINATIONS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ATTENDANCE: ['VIEW', 'UPDATE', 'APPROVE'],
    LEAVES: ['VIEW', 'APPROVE']
  },
  DEAN: {
    LMS_COURSE: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LESSON: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    HOMEWORK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ASSIGNMENT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SUBMISSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUESTION_BANK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUIZ: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ONLINE_CLASS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    DISCUSSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    GRADEBOOK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LEARNING_ANALYTICS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    STUDENTS: ['VIEW', 'EXPORT'],
    EXAMINATIONS: ['VIEW', 'APPROVE', 'EXPORT'],
    THESIS_RESEARCH: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    EMPLOYEES: ['VIEW']
  },
  HEAD_OF_DEPARTMENT: {
    LMS_COURSE: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LESSON: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    HOMEWORK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ASSIGNMENT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SUBMISSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUESTION_BANK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    QUIZ: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ONLINE_CLASS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    DISCUSSION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    GRADEBOOK: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LEARNING_ANALYTICS: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    STUDENTS: ['VIEW', 'EXPORT'],
    EXAMINATIONS: ['VIEW', 'APPROVE', 'EXPORT'],
    TIMETABLE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE'],
    THESIS_RESEARCH: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE']
  },
  COORDINATOR: {
    STUDENTS: ['VIEW', 'UPDATE'],
    EXAMINATIONS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    ATTENDANCE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE'],
    TIMETABLE: ['VIEW', 'CREATE', 'UPDATE']
  },
  TEACHER: {
    LMS_COURSE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    LESSON: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    HOMEWORK: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    ASSIGNMENT: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    SUBMISSION: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    QUESTION_BANK: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    QUIZ: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    ONLINE_CLASS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    DISCUSSION: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    GRADEBOOK: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    LEARNING_ANALYTICS: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    STUDENTS: ['VIEW', 'EXPORT', 'PRINT'],
    ATTENDANCE: ['VIEW', 'CREATE', 'UPDATE'],
    EXAMINATIONS: ['VIEW'],
    MARKS_ENTRY: ['VIEW', 'CREATE', 'UPDATE'],
    TIMETABLE: ['VIEW'],
    HIFZ_TRACKER: ['VIEW', 'CREATE', 'UPDATE']
  },
  FACULTY: {
    STUDENTS: ['VIEW'],
    ATTENDANCE: ['VIEW', 'CREATE', 'UPDATE'],
    MARKS_ENTRY: ['VIEW', 'CREATE', 'UPDATE'],
    THESIS_RESEARCH: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE'],
    TIMETABLE: ['VIEW']
  },
  ACCOUNTANT: {
    FEES_INVOICES: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ACCOUNTING_LEDGER: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PAYROLL: ['VIEW', 'CREATE', 'UPDATE', 'EXPORT', 'PRINT', 'MANAGE'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  HR_MANAGER: {
    EMPLOYEES: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    POSITION: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    RECRUITMENT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    CANDIDATE: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    ATTENDANCE_HR: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SHIFT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    LEAVES: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    OVERTIME: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PERFORMANCE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    TRAINING: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    DISCIPLINE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    GRIEVANCE: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    SEPARATION: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    PAYROLL: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT'],
    REPORTS: ['VIEW', 'EXPORT', 'PRINT']
  },
  LIBRARIAN: {
    LIBRARY: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE']
  },
  HOSTEL_MANAGER: {
    HOSTEL: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE']
  },
  TRANSPORT_MANAGER: {
    TRANSPORT: ['VIEW', 'CREATE', 'UPDATE', 'DELETE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE']
  },
  ADMISSION_OFFICER: {
    ADMISSION: ['VIEW', 'CREATE', 'UPDATE', 'APPROVE', 'EXPORT', 'PRINT', 'MANAGE'],
    STUDENTS: ['VIEW', 'CREATE']
  },
  STUDENT: {
    LMS_COURSE: ['VIEW'],
    LESSON: ['VIEW'],
    HOMEWORK: ['VIEW'],
    ASSIGNMENT: ['VIEW'],
    SUBMISSION: ['VIEW', 'CREATE', 'UPDATE'],
    QUIZ: ['VIEW', 'CREATE'],
    ONLINE_CLASS: ['VIEW'],
    DISCUSSION: ['VIEW', 'CREATE'],
    GRADEBOOK: ['VIEW'],
    LEARNING_ANALYTICS: ['VIEW'],
    STUDENTS: ['VIEW'],
    ATTENDANCE: ['VIEW'],
    EXAMINATIONS: ['VIEW'],
    TRANSCRIPTS: ['VIEW', 'PRINT'],
    FEES_INVOICES: ['VIEW', 'PRINT'],
    LIBRARY: ['VIEW'],
    HIFZ_TRACKER: ['VIEW'],
    THESIS_RESEARCH: ['VIEW', 'CREATE']
  },
  PARENT: {
    STUDENTS: ['VIEW'],
    ATTENDANCE: ['VIEW'],
    EXAMINATIONS: ['VIEW', 'PRINT'],
    TRANSCRIPTS: ['VIEW', 'PRINT'],
    FEES_INVOICES: ['VIEW', 'PRINT'],
    HIFZ_TRACKER: ['VIEW'],
    TRANSPORT: ['VIEW']
  }
};
