import { AppError } from '../errors/app-error';

export type PlatformPermission =
  | 'PLATFORM_VIEW_DASHBOARD'
  | 'TENANT_VIEW'
  | 'TENANT_CREATE'
  | 'TENANT_UPDATE'
  | 'TENANT_SUSPEND'
  | 'TENANT_IMPERSONATE'
  | 'PLAN_VIEW'
  | 'PLAN_CREATE'
  | 'PLAN_UPDATE'
  | 'PLAN_ARCHIVE'
  | 'SUBSCRIPTION_VIEW'
  | 'SUBSCRIPTION_MANAGE'
  | 'ORDER_VIEW'
  | 'PAYMENT_VIEW'
  | 'PAYMENT_MANAGE'
  | 'GATEWAY_VIEW'
  | 'GATEWAY_MANAGE'
  | 'DEMO_CREDENTIAL_VIEW'
  | 'DEMO_CREDENTIAL_RESET'
  | 'DEMO_CLIENT_EXPORT'
  | 'PLATFORM_USER_VIEW'
  | 'PLATFORM_USER_MANAGE'
  | 'PLATFORM_SETTINGS_VIEW'
  | 'PLATFORM_SETTINGS_MANAGE'
  | 'AUDIT_VIEW'
  | 'SUPPORT_TICKET_VIEW'
  | 'SUPPORT_TICKET_REPLY'
  | 'SUPPORT_TICKET_ASSIGN'
  | 'SUPPORT_TICKET_STATUS'
  | 'SUPPORT_TICKET_ESCALATE'
  | 'SUPPORT_INTERNAL_NOTE'
  | 'SUPPORT_CLOSE'
  | 'SUPPORT_SLA_MANAGE'
  | 'KNOWLEDGE_MANAGE'
  | 'TRAINING_MANAGE'
  | 'CONTACT_INQUIRY_MANAGE'
  | 'CONTACT_SETTINGS_MANAGE';

export const PLATFORM_ROLE_PERMISSIONS: Record<string, PlatformPermission[]> = {
  PLATFORM_SUPER_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'TENANT_CREATE',
    'TENANT_UPDATE',
    'TENANT_SUSPEND',
    'TENANT_IMPERSONATE',
    'PLAN_VIEW',
    'PLAN_CREATE',
    'PLAN_UPDATE',
    'PLAN_ARCHIVE',
    'SUBSCRIPTION_VIEW',
    'SUBSCRIPTION_MANAGE',
    'ORDER_VIEW',
    'PAYMENT_VIEW',
    'PAYMENT_MANAGE',
    'GATEWAY_VIEW',
    'GATEWAY_MANAGE',
    'DEMO_CREDENTIAL_VIEW',
    'DEMO_CREDENTIAL_RESET',
    'DEMO_CLIENT_EXPORT',
    'PLATFORM_USER_VIEW',
    'PLATFORM_USER_MANAGE',
    'PLATFORM_SETTINGS_VIEW',
    'PLATFORM_SETTINGS_MANAGE',
    'AUDIT_VIEW',
    'SUPPORT_TICKET_VIEW',
    'SUPPORT_TICKET_REPLY',
    'SUPPORT_TICKET_ASSIGN',
    'SUPPORT_TICKET_STATUS',
    'SUPPORT_TICKET_ESCALATE',
    'SUPPORT_INTERNAL_NOTE',
    'SUPPORT_CLOSE',
    'SUPPORT_SLA_MANAGE',
    'KNOWLEDGE_MANAGE',
    'TRAINING_MANAGE',
    'CONTACT_INQUIRY_MANAGE',
    'CONTACT_SETTINGS_MANAGE'
  ],
  SUPER_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'TENANT_CREATE',
    'TENANT_UPDATE',
    'TENANT_SUSPEND',
    'TENANT_IMPERSONATE',
    'PLAN_VIEW',
    'PLAN_CREATE',
    'PLAN_UPDATE',
    'PLAN_ARCHIVE',
    'SUBSCRIPTION_VIEW',
    'SUBSCRIPTION_MANAGE',
    'ORDER_VIEW',
    'PAYMENT_VIEW',
    'PAYMENT_MANAGE',
    'GATEWAY_VIEW',
    'GATEWAY_MANAGE',
    'DEMO_CREDENTIAL_VIEW',
    'DEMO_CREDENTIAL_RESET',
    'DEMO_CLIENT_EXPORT',
    'PLATFORM_USER_VIEW',
    'PLATFORM_USER_MANAGE',
    'PLATFORM_SETTINGS_VIEW',
    'PLATFORM_SETTINGS_MANAGE',
    'AUDIT_VIEW',
    'SUPPORT_TICKET_VIEW',
    'SUPPORT_TICKET_REPLY',
    'SUPPORT_TICKET_ASSIGN',
    'SUPPORT_TICKET_STATUS',
    'SUPPORT_TICKET_ESCALATE',
    'SUPPORT_INTERNAL_NOTE',
    'SUPPORT_CLOSE',
    'SUPPORT_SLA_MANAGE',
    'KNOWLEDGE_MANAGE',
    'TRAINING_MANAGE',
    'CONTACT_INQUIRY_MANAGE',
    'CONTACT_SETTINGS_MANAGE'
  ],
  PLATFORM_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'TENANT_CREATE',
    'TENANT_UPDATE',
    'TENANT_SUSPEND',
    'TENANT_IMPERSONATE',
    'PLAN_VIEW',
    'PLAN_CREATE',
    'PLAN_UPDATE',
    'SUBSCRIPTION_VIEW',
    'SUBSCRIPTION_MANAGE',
    'ORDER_VIEW',
    'PAYMENT_VIEW',
    'GATEWAY_VIEW',
    'DEMO_CREDENTIAL_VIEW',
    'DEMO_CLIENT_EXPORT',
    'PLATFORM_USER_VIEW',
    'PLATFORM_SETTINGS_VIEW',
    'AUDIT_VIEW',
    'SUPPORT_TICKET_VIEW',
    'SUPPORT_TICKET_REPLY',
    'SUPPORT_TICKET_ASSIGN',
    'SUPPORT_TICKET_STATUS',
    'SUPPORT_TICKET_ESCALATE',
    'SUPPORT_INTERNAL_NOTE',
    'SUPPORT_CLOSE',
    'KNOWLEDGE_MANAGE',
    'TRAINING_MANAGE',
    'CONTACT_INQUIRY_MANAGE',
    'CONTACT_SETTINGS_MANAGE'
  ],
  BILLING_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'PLAN_VIEW',
    'SUBSCRIPTION_VIEW',
    'SUBSCRIPTION_MANAGE',
    'ORDER_VIEW',
    'PAYMENT_VIEW',
    'PAYMENT_MANAGE',
    'GATEWAY_VIEW',
    'AUDIT_VIEW',
    'CONTACT_INQUIRY_MANAGE'
  ],
  SUPPORT_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'TENANT_IMPERSONATE',
    'PLAN_VIEW',
    'SUBSCRIPTION_VIEW',
    'AUDIT_VIEW',
    'SUPPORT_TICKET_VIEW',
    'SUPPORT_TICKET_REPLY',
    'SUPPORT_TICKET_ASSIGN',
    'SUPPORT_TICKET_STATUS',
    'SUPPORT_TICKET_ESCALATE',
    'SUPPORT_INTERNAL_NOTE',
    'SUPPORT_CLOSE',
    'SUPPORT_SLA_MANAGE',
    'KNOWLEDGE_MANAGE',
    'TRAINING_MANAGE',
    'CONTACT_INQUIRY_MANAGE'
  ],
  SALES_ADMIN: [
    'PLATFORM_VIEW_DASHBOARD',
    'TENANT_VIEW',
    'PLAN_VIEW',
    'ORDER_VIEW',
    'DEMO_CREDENTIAL_VIEW',
    'DEMO_CLIENT_EXPORT',
    'CONTACT_INQUIRY_MANAGE'
  ]
};

export function hasPlatformPermission(session: any, permission: PlatformPermission): boolean {
  if (!session || (!session.isPlatformAdmin && !session.user?.isPlatformAdmin)) {
    return false;
  }

  const role = session.role || session.user?.role || '';
  const perms = PLATFORM_ROLE_PERMISSIONS[role] || [];
  return perms.includes(permission);
}

export function requirePlatformPermission(session: any, permission: PlatformPermission): void {
  if (!hasPlatformPermission(session, permission)) {
    throw AppError.forbidden(`Platform permission denied: Requires '${permission}' authorization.`);
  }
}
